C = 30      #ASIGNAR 30 A LA VARIABLE C
F = (C *9/5+32)     #OPERAR EQUIVALENTE EN Fº DE C Y ASIGNAR A VARIABLE F
print (F)       #IMPRIMIR VALOR DE F

F = 77      #ASIGNAR A LA VARIABLE F 77
C =((F-32)*5/9)       #OPERAR EQUIVALENTE EN Cº DE F Y ASIGNAR A VARIABLE C
print (C)       #IMPRIMIR VALOR DE C
